syntax = "proto3";

package car_rental.v1;

option go_package = "go-kozadayev-exercise/task8/api/proto;rentalv1";


service RentalService {
  rpc CreateBooking(CreateBookingRequest) returns (Booking) {
  }
  rpc CheckAvailability(CheckAvailabilityRequest) returns (CheckAvailabilityResponse) {
  }
}

message Booking {
  int64 id = 1;
  int64 car_id = 2;
  int64 start_date = 3;
  int64 end_date = 4;
}

message CreateBookingRequest {
  int64 car_id = 1;
  int64 start_date = 2;
  int64 end_date = 3;
}

message CheckAvailabilityRequest {
  int64 car_id = 1;
  int64 start_date = 2;
  int64 end_date = 3;
}

message CheckAvailabilityResponse {
  bool available = 1;
}
