syntax = "proto3";

package canbus.v1;

option go_package = "go-kozadayev-exercise/task9/api/proto;canbusv1";


service CanBusService {
  rpc TelemetryStream(stream Signal) returns (stream Alert);
  
  rpc GetAlerts(GetAlertsRequest) returns (GetAlertsResponse) {
  }
}

message Signal {
  string device_id = 1;
  string name = 2; // speed, rpm
  float value = 3;
}

message Alert {
  string device_id = 1;
  string message = 2;
  int64 timestamp = 3;
}

message GetAlertsRequest {
  int64 start_time = 1;
  int64 end_time = 2;
}

message GetAlertsResponse {
  repeated Alert alerts = 1;
}
