syntax = "proto3";

package car.v1;

option go_package = "go-kozadayev-exercise/task1/api/proto;carv1";

import "google/api/annotations.proto";

service CarService {
  rpc CreateCar(CreateCarRequest) returns (CreateCarResponse) {
    option (google.api.http) = {
      post: "/v1/cars"
      body: "*"
    };
  }
  rpc GetCar(GetCarRequest) returns (GetCarResponse) {
    option (google.api.http) = {
      get: "/v1/cars/{vin}"
    };
  }
}

message Car {
  string vin = 1;
  string brand = 2;
  string model = 3;
  int32 year = 4;
}

message CreateCarRequest {
  string vin = 1;
  string brand = 2;
  string model = 3;
  int32 year = 4;
}

message CreateCarResponse {
  Car car = 1;
}

message GetCarRequest {
  string vin = 1;
}

message GetCarResponse {
  Car car = 1;
}
